#!/bin/bash
#echo "Enter input base: "
read -p "Enter input base > " inputBase
#echo "Enter Value: "
read -p "Enter value > " value
#echo "Enter output base: "
read -p "Enter output base > " outputBase

echo "****************************"

if [[ $inputBase == 10 ]]; then
	echo "obase=$outputBase; $value" | bc
else
	echo "obase=$outputBase; ibase=$inputBase;  $value" | bc
fi
