#!/bin/bash
read -p "Enter input base > " inputBase
read -p "Enter value > " value
read -p "Enter output base > " outputBase

echo "****************************"

if [[ $inputBase == 10 ]]; then
	echo "obase=$outputBase; $value" | bc
else
	echo "obase=$outputBase; ibase=$inputBase;  $value" | bc
fi
